apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    appname: node-app-deployment
    component: frontend
spec:
  selector:
    matchLabels:
      appname: node-app-deployment
      component: frontend
  template:
    metadata:
      labels:
        appname: node-app-deployment
        component: frontend
    spec:
      containers:
      - name: websrv-images
        image: 844099387134.dkr.ecr.us-east-1.amazonaws.com/websrv-images:v0.1
        ports:
        - containerPort: 8081