apiVersion: v1
kind: Service
metadata:
  name: node-app-np
  labels:
    appname: node-app-deployment
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 30000
  selector:
    appname: node-app-deployment
    component: frontend