apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  labels:
    appname: node-app-deployment
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    appname: node-app-deployment