apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    appname: flask-app
    component: greeting
spec:
  selector:
    matchLabels:
      appname: flask-app
      component: greeting
  template:
    metadata:
      labels:
        appname: flask-app
        component: greeting
    spec:
      containers:
      - name: flask-webserver
        image: 844099387134.dkr.ecr.us-east-1.amazonaws.com/flask-webserver:v0.1
        ports:
        - containerPort: 5000